### ISSUE TITLE
bad edit option "canundo"

### ISSUE THREAD

**Issue by blacksqr** [aplsimple/alited#1]
Just downloaded the latest version today (1.0.6b13), started it up for the first time, and after selecting the config file location got the following error:

bad edit option "canundo": must be modified, redo, reset, separator, or undo
    while executing
"::.alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text.internal edit canundo"
    ("eval" body line 1)
    invoked from within
"eval ::.alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text.internal $args"
    (procedure ".alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text" line 1)
    invoked from within
"$wtxt edit canundo"
    (procedure "alited::edit::CheckUndoRedoIcons" line 9)
    invoked from within
"alited::edit::CheckUndoRedoIcons [alited::main::CurrentWTXT] $TID"
    (procedure "alited::bar::OnTabSelection" line 10)
    invoked from within
"{*}[string map [list %t $TID] $com2]"
    (class "::bartabs::Bar" method "Bar_Cmd2" line 7)
    invoked from within
"my {*}$args"
    (object "::alited::bar::al(bts)" method "bar0" line 1)
    invoked from within
"my $BID Bar_Cmd2 -csel2 $TID "
    (class "::bartabs::Tab" method "Tab_BeCurrent" line 12)
    invoked from within
"my {*}$args"
    (object "::alited::bar::al(bts)" method "tab0" line 1)
    invoked from within
"my $TID Tab_BeCurrent"
    (class "::bartabs::Tab" method "show" line 27)
    invoked from within
"my {*}$args"
    (object "::alited::bar::al(bts)" method "tab0" line 1)
    invoked from within
"my {*}$args"
    (object "::alited::bar::al(bts)" method "bar0" line 1)
    invoked from within
"al(bts) $al(BID) {*}$args"
    (procedure "alited::bar::BAR" line 6)
    invoked from within
"alited::bar::BAR $TID show"
    (procedure "alited::file::NewFile" line 8)
    invoked from within
"alited::file::NewFile"
    (procedure "::alited::file::CheckForNew" line 7)
    invoked from within
"::alited::file::CheckForNew yes"
    ("after" script)

**Comment by aplsimple** [comment]
Hi,

You should update your Tcl/Tk version, say, to 8.6.11. The text's canundo
feature appears afaik in 8.6.6.

Another way is using stand-alone tclkits instead of tclsh/wish. If you are
on Windows, this link has them a lot:
http://tclkits.rkeene.org/fossil/wiki/Downloads

I should be more exact on this at installing alited.

чт, 16 дек. 2021 г., 23:02 blacksqr ***@***.***>:

**Comment by blacksqr** [comment]
Upgrading to Tk 8.6.11 solved the problem.  I suggest adding "package require Tk 8.6.11" to the startup code.

**Comment by aplsimple** [comment]
A check for canundo and a recommendation to upgrade Tcl/Tk version were included in 1.0.6b14.

Also, alited is updated first in its fossil repo. The github one is for more or less "stable" versions. I.e. to get the fresh version, use this chiselapp link:

https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip
