### ISSUE TITLE
tkcon and env

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#12]
When using alited under Linux Debian.
When I run tkcon from alited the array ::env looks different than when I call tkcon in the terminal or as a package in tclsh/wish without alited.
It looks to me as if tkcon (alited) does not access /etc/profile, ~/.bashrc, ~/.profile or ~/.xprofile, but only /etc/login.defs.
Is this a peculiarity of alited? It is then irritating if I have created .bashrc or .profile as additional paths for libarary. Can I set something in alited?

**Comment by aplsimple** [comment]
Thank you for the feedback.

Yes, alited uses a bit modified version of tkcon 2.7, located in alited-dir/lib/util directory.

Just now, I really don't know why it doesn't see ~/.bashrc etc. It needs some searches.

Though you can try to attach a standard version /usr/bin/tkcon to alited, this way:
 - right click somewhere in the alited's tool bar
 - choose "Open bar-menu settings"
 - in one of the bottom empty rows, click the icon selector and choose, say, "K" to be the future toolbar icon for tkcon
 - in the command selector of the row (right button), select Utils / Tcl/Tk / Tkcon command
 - Click "Save" button to restart alited
The "K" icon should appear in the toolbar to run /usr/bin/tkcon

#_______________________

You might also try replacing alited-dir/lib/util/tkcon.tcl with the standard (obviously of newer version, e.g. mine is 2.7.1) tkcon from /usr/share/tcltk/tkcon

If it will work as you want, please, tell me what version of it is used in your machine. I'd try to update my cracked version with it.

**Comment by gregnix** [comment]
alited : tkcon v2.7 cvs v1.123 2015/10/20
linux Debian: tkcon v2.7.10 cvs v1.119 2012/12/27

Added as described in alited's tool bar tkcon.
array ::env is just like the tkcon from alited.
It's the same with F4 menu-utils-Tcl/Tk-tclsh

So array ::env differs whether I use it in (1) alited (tkcon, tclsh) or directly in (2) terminal (Linux) (tkcon , tclsh).

In (2) the entries are taken from .bashrc and .profile.
So it's not because of tkcon, but because of alited or my Linux system.

**Comment by gregnix** [comment]
Start alited from the desktop

[Desktop Entry]
Type=Application
Name=Alited
Exec=/usr/bin/env tclsh /home/greg/programs/share/alited/src/alited.tcl %F
Icon=Alited
Terminal=false
Categories=Development;
Comment=Tcl/Tk script editor;TextEditor;Development;IDE;

**Comment by gregnix** [comment]
I also installed e_menu as a program.
  e_menu 4.2.2

If I call e_menu (-> tclsh) directly without alited it is also
the array ::env without the additional entries.
Could maybe be a n e_menu or my Linux system.

**Comment by aplsimple** [comment]
Hi Gregor,

May it be so that your ~/.bashrc needs a bit rearranging?

Namely: try defining your environment variables in the beginning of the ~/.bashrc, not in its ending lines.

I had the same issues with some environment variables. They were solved after those changes to ~/.bashrc.

**Comment by gregnix** [comment]
Hello,
tclsh (e_menu)
env(PATH)                     = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

tried different .bashrc and .profiles, all have no effect when the tclsh is started by e_menu.
Since the problem probably only occurs with me, you can close the iusses here.
It is not a mistake of alited.

**Comment by aplsimple** [comment]
Not sure, maybe this will help.

In my Debian, I have this ~/. bashrc file's beginning:

    # ~/.bashrc: executed by bash(1) for non-login shells.
    # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
    # for examples
    export TCLLIBPATH="/usr/share/tcltk/tklib0.7 /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/treectrl2.4.1 /usr/lib/tcltk/x86_64-linux-gnu/Img1.4.13"
...

and in ~/.profile there is a line:

    export PATH="$PATH:/home/apl/UTILS"

Both environment variables are seen by tkcon when it's run from alited, their values being same as in the terminal run independently. 

Especially TCLLIBPATH variable is valuable to supply the list of pathes where Tcl will search additional packages.

Let the issue be open a while, perhaps someone would help with it better than me.
