### ISSUE TITLE
Small optimization from RADXIDE treeview code

### ISSUE THREAD

**Issue by par7133** [aplsimple/alited#13]
Hello Alex,

Here a small optimization from RADXIDE.

If you look into your tree code (and sorry if I'm not more detailed) you can
move out from getDirectoryContent() to createFileTree() the following lines:

set al(_dirignore) [list]
catch {    ;# there might be an incorrect list -> catch it
  foreach d $al(prjdirignore) {
    lappend al(_dirignore) [string toupper [string trim $d \"]]
     }  
} 

and set it just before this foreach:

foreach item [getDirectoryContent $project(ROOT)] {

I have plenty of changes in my code. I am sorry if transport optimizations like this one to Alited
it is not always so obvious..

Hope this helps.

== Capitan Cloud

**Comment by aplsimple** [comment]
Hi Daniele,

Thank you a lot for the advice.
I've included it into v1.6.1 to come in 27 dec.
