### ISSUE TITLE
Question about alited and two monitors

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#17]
I have two monitors. I would like to see alited with the program code on one monitor and the executed program and the output of the terminal on the other monitor.
I can definitely post something about it in alited or project-related.
Looking for an approach or tip on how I could do this.

Gregor

**Comment by aplsimple** [comment]
I have no multiple monitors, so can't offer something special.

Still if I were you I would try using saved/restored geometry of your app.

At closing the app, you save its geometry to a configuration file, at starting the app you read the geometry from the file and restore it. Both actions use *wm geometry* command.

Thus, when your app is on a left monitor, its geometry might look like this:
500x300+-3100+200

and on a right monitor like this:
500x300+2400+200

I.e the X coordinates are shifted to left or right.

As for terminal output, it is another problem. I have no ideas on this presently, except for having an open terminal on another monitor and starting apps from it manually.
