### ISSUE TITLE
Can't define new project

### ISSUE THREAD

**Issue by blacksqr** [aplsimple/alited#2]
alited 1.0.6b13 on Lunux with Tcl/Tk 8.6.11

I start the program for the first time, specify a config location, define a new project in the projects window by editing the "Project name:" and "Root directory:" fields, and when I click the "Select" button, the error below appears. The project is not saved after the error window is closed.

 ERROR file::DisplayFile:  
 () .alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text !=   
 Please, notify alited's authors!

    while executing
"alited::file::DisplayFile $TID $curfile $wtxt $doreload"
    (procedure "GetText" line 72)
    invoked from within
"GetText $TID yes"
    (procedure "alited::main::ShowText" line 6)
    invoked from within
"alited::main::ShowText"
    ("after" script)

**Comment by blacksqr** [comment]
I can define a project if after providing the name and root directory I hit the button to the left with the green plus icon.  The error only comes when I hit the "Select" button on the right.

**Comment by blacksqr** [comment]
If after defining a project I quit and restart alited, when I open the project window, click on the project I just created, and click the "Select" button, the same error as above appears.

**Comment by blacksqr** [comment]
This error seems to occur because when I defined the project, I hit the "Add" button or the "Substitute" button in the "Add a project" window.

If I define a new project, and hit the "Don't change" button, the project is created.

Sorry about the stream of consciousness reports.  I'm trying to work through learning the program.

**Comment by blacksqr** [comment]
Sorry again about the confused reporting.  The error always appears when I hit the "Select" button in the Projects window.  No other steps seem relevant.  If I dismiss the error and continue, the new project is opened and the program seems to work as expected.

**Comment by blacksqr** [comment]
If I create a project, then click on the default project in the Projects window, then click on my new project and click the Select button, the new project will open without an error.

**Comment by aplsimple** [comment]
I should simplify this thing.

Really, too much choices at the project creation, all those change/not change etc. For now, the best way to create a new project is:
- enter a project name
- enter a path to its root directory
- hit [+] button
- hit "Not change" at the follow-up question

The button "Select" makes sense only after these steps. I should check if a user tries enter a new project and hit "Select" before saving it.

If you can choose between Windows and Linux for a work with alited, I would recommend Linux. The Windows version of alited is raw yet, namely some e_menu stuff not working.

Also, alited is updated first in its fossil repo. The github one is for more or less "stable" versions. I.e. to get the fresh version, use this chiselapp link:

https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip

**Comment by aplsimple** [comment]
The changes made:
- introducing message at entering "Projects" (to be hidden)
- Add / Change / Delete without superfluous warnings
- Select button barks at a non-existing project
- tiny-ups for notes / reminders

Changes available at 
https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip

**Comment by blacksqr** [comment]
The new version is much improved, thanks.  There's still one place where I get an error.  I take the following steps:

1. Start alited
2. open the Projects window
3. type in a new project name and project root.
4. Click Select button.  The warning that the project doesn't exist yet appears.
5. Click the + button.  Message that project has been created appears.
6. Click Select button.  The project appears to be selected correctly, but the following error pops up:

 ERROR file::DisplayFile:  
 () .alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text !=   
 Please, notify alited's authors!

    while executing
"alited::file::DisplayFile $TID $curfile $wtxt $doreload"
    (procedure "GetText" line 72)
    invoked from within
"GetText $TID yes"
    (procedure "alited::main::ShowText" line 6)
    invoked from within
"alited::main::ShowText"
    ("after" script)

**Comment by aplsimple** [comment]
It's all about the importance of asserts. "That's impossible to appear but that appears". I should look into this issue closer. And try *assert* of tcllib instead of home-made checks. There are other places waiting for it.
Thanks for your scrutinizing notes!

**Comment by aplsimple** [comment]
I've made changes (project.tcl) to solve this problem. Pitifully I should decline *control::assert* because of *control* package isn't in basic tclkits with Tk. I use tclkits (e.g. made by BAWT) as sort of "core Tcl/Tk set of packages". By the way, this was the reason for using treeview instead of tablelist, everywhere in alited's appropriate places.

Changes available at
https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip

**Comment by blacksqr** [comment]
Assert no longer appears in v1.0.6b26
