### ISSUE TITLE
linux: custom terminal does not launch, no error messages

### ISSUE THREAD

**Issue by johannish** [aplsimple/alited#20]
When I choose "konsole" or one of the other available terminals, the F5 or "Run" button does nothing, and no error is output to the terminal where I started alited (whether running `./alited.sh` or `wish src/src/alited.tcl`). Only by clicking "Run e_menu" > "Run Tcl {all selection}" do I see the error message in a wish window:
```
couldn't execute "konsole": no such file or directory
```
I found Setup > Preferences > Tools and typed in the terminal of my choice: `xfce4-terminal` or `/usr/bin/xfce4-terminal`. No matter how I choose to run, the terminal is not launched and there is no output to the terminal where alite was started. With this configuration, there is also no error "no such file or directory" shown--all Run options are simply silent/broken.

(I did discover the way to run in tkcon by default, which is a workaround for now.)

What am I missing? (And thanks for this neat little editor!)

**Comment by aplsimple** [comment]
Hi,

Thanks for the feedback.

The problem is with xfce4-terminal, obviously your default one. It treats -x option in the same way as others do -e.

I'll try to correct this on Wednesday. Also, maybe I'll place "Test" button at right side of terminal setting of Preferences/Tools.

Side note. My personal working variant is lxterminal, it's present in the preferences list. I like it mostly for its --geometry option and menu bar. If it doesn't lead to a lot of downloaded dependencies, you might try to install and use the lxterminal instead of xfce4-terminal.

**Comment by aplsimple** [comment]
Fixed in version 1.8.5b1.

**Comment by johannish** [comment]
Thank you! I tested it and it's working fine.

Two more suggestions for you:
1. If the error message for my terminal were exposed somewhere, I would have taken a stab at fixing this myself first (perhaps with a custom shell script wrapper); I'm not sure where I could have seen the exception. I don't expect you to support my every use case, though I do appreciate your speedy fix here!
2. You might consider a different approach to supporting terminals: a template format where the user inputs the terminal arguments with placeholders. Something like `xfce4-terminal -x %s` where `%s` is substituted with the tcl interpreter/script.

Regardless, thank you for a useful tool!

**Comment by aplsimple** [comment]
Thanks for the suggestions.

The 1st suggestion isn't clear for me. Could you put more details, possibly an example, understandable for dummies like me?

I might do the 2nd suggestion, probably this way: in Tools/Run... dialogue the "combined" mode (rather fanciful) might be replaced with something like "direct call" which is that you suggested. As for the wildcards: in Tools/Run... dialogue, %f (edited file name) and  %d, %pd, %H, %s (see Help) are already supported.
