### ISSUE TITLE
Multiple file view at the same time

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#21]
Hello!
Great editor, thank you for all the hard work!
Question - is it possible to open multiple files side by side? Like here in notepad:
![image](https://github.com/aplsimple/alited/assets/113975847/acaa7d88-fd7a-4994-829d-b338457800d5)

Very often it is a really necessary option for comforting copying from one file to another.
Thank you in advance, George.

**Comment by aplsimple** [comment]
Hi George,
Thanks for the feedback.

To implement your suggestion as it's presented by the screenshot, I had to plan it from the very beginning, alas.

Though rarely, this mode is necessary indeed. In such cases I just open another editor for a parallel file and place it aside by alited, optionally making it "staying topmost".

When I need to compare a file's versions, I just call Differences (of alited's tools). This is customized to kdiff3 by default, still I prefer meld.

Nonetheless, I could make a "File / Detach" menu item - when a currently edited file is detached to another editor window placed aside by the current editing frame. This parallel window would be above the main window of alited and serve as an "errand boy" only, i.e. no alited's functionality except editing.

**Comment by georgtree** [comment]
Hello, the last proposal from your message sounds great, often the second window is needed just for comfort copying of code and/or just look at it.
Thank you in advance!

**Comment by georgtree** [comment]
Hello!
Just tested the new feature - it works well, thank you!
The only question - how to enable syntax highlighting in this window?

**Comment by aplsimple** [comment]
It's only a draft, skeleton sort of. Of course, there will be syntax highlighting and saved geometries of first 8 windows. Also, the feature will be available in the context menus of tab bar, file viewer and Projects/Files.

**Comment by georgtree** [comment]
Great, looking forward to final version!

**Comment by aplsimple** [comment]
I think this is done, though without docs yet.

**Comment by georgtree** [comment]
All works great, thank you very much!

**Comment by georgtree** [comment]
Hello, found an exception here - if I detach new file and that file has not been saved, the detach doesn't work

**Comment by georgtree** [comment]
And the other one - while using WSL with detach, it doesn't allow me to edit main window files, because cursor is always on focus in detached window

**Comment by aplsimple** [comment]
George,

I've changed something in this feature, hopefully, to better side.

As for your remarks: 
 1) for the new file, alited will offer to save it first, then detach it; imo the detachment of "no name" text looks weird;
 2) the currently edited text will be refocused after detachments.

**Comment by georgtree** [comment]
Got it, thank you!
