### ISSUE TITLE
Add *test* keyword to unit tree as a leaf

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#25]
Hello!
Is it possible to add test keyword to the unit tree of alited as a leaf, the same as procs and methods?
I have dozens of tests and would be great to see them in the unit tree...
Thank you in advance!

**Comment by georgtree** [comment]
I see that there is an option to define custom comment form for the unit, but doesn't see the same thing for leafs...

**Comment by aplsimple** [comment]
To do this, in Preferences/Units, modify the field **Proc's regexp** so that it includes **|test** after **proc|method**

The Standard button should do it, and as it doesn't I'll look why not.

**Comment by aplsimple** [comment]
Okay, I added **test** for the Standard button of Preferences/Units. In v1.8.6.1.

Use the Standard button if you didn't modify other fields, otherwise just change two fields containing **proc|method** (to **proc|method|test**).

**Comment by georgtree** [comment]
All works, great, thank you very much!
