### ISSUE TITLE
Error with tips on windows

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#26]
Hello!
I tried to run Alited on Windows, and got this strange error - when I open file not from the project folder,
and put mouse on it's tab, the error appears immediately:

wrong # args: should be "::baltip::my::Show w text force geo optvals"
wrong # args: should be "::baltip::my::Show w text force geo optvals"
    while executing
"::baltip::my::Show .alwin.fra.fra.pan.panR.fraTop.panTop.btsBar.frame.tab4000004.l C:/Users/nx023666/Documents/tcl_tools/gnuplotutil-1.0.tm"
    (command bound to event)

I suspect that it is something with tip balloon, it triggered when Alited tries to show baltip at this particular tab.
Thank you in advance!

P.S. I even can't close the already opened file because of this error :(

**Comment by aplsimple** [comment]
I would like to ask a favour of you.

Take and show me two screenshots of alited's Help/About - 1st tab (Info) and 2nd tab (Packages). Thanks in advance.

**Comment by aplsimple** [comment]
Also, please describe all your steps to get the error. Details are important.

The problem is that I can't reproduce this error however tried. The only line containing the bind (Enter event to baltip::my::Show) is well formed, so I don't understand why it leads to so miserable result.

**Comment by georgtree** [comment]
![image](https://github.com/user-attachments/assets/9233391f-a5be-44fa-a5bb-886dccd4fefa)
![image](https://github.com/user-attachments/assets/3e9eb274-c6af-4d6a-869c-a55d6d7d2a54)

The steps to error reproduce:
1) open project in alited
2) through menu open I open file from another alited project, it appears ok, but when I put mouse on a tab name. the error appears

**Comment by aplsimple** [comment]
George,

Thanks for your response.

I can reproduce the issue, though not with the same error message as yours, still of the same type. 

Anyway it will be solved.

The problem's source is the used Tcl/Tk executable - **wish8.7**, as seen in Help/About of your screenshot.

If you run **alited.tcl** with a regular **tclsh**, say of **Magicsplat** distribution, the error would be not shown, highly likely.

So, perhaps, it's a reason to send a bug report for TCT, after a scrupulous analysis of course. TCT would be grateful to both of us:)

**Comment by georgtree** [comment]
Hello, yes you are right, I have ActiveTcl distribution on my PC, and the issue disappeared with it

**Comment by aplsimple** [comment]
Yes, it was a bug of wish8.7,  namely: tk_getOpenFile added a control character to the selected file name. TCT fixed it.

I've downloaded the updated wish8.7 executables, without this bug.

After some testing both, the alited's installers for Windows and Linux will be updated too. Hopefully this week.

**Comment by georgtree** [comment]
Great, good news, thank you!

**Comment by aplsimple** [comment]
OK, the installers updated. Also, v1.8.6.2 uploaded.
