### ISSUE TITLE
Run files from current user bash session

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#27]
Hello!
Question - when I run tclsh from terminal with script all works, like ```tclsh doc_gen.tcl```
When I run this way:
![image](https://github.com/user-attachments/assets/9098fc2b-4240-4acd-b889-ad9a439c0bb4)

I got this:
![image](https://github.com/user-attachments/assets/9dd9652c-b2f3-4fe3-ba12-1e86c536f750)

looks like it doesn't see the user folder that contains ruff! package, I set TCLLIBPATH env variable in .bashrc.
Could you help please? Thank you.

**Comment by georgtree** [comment]
I found the issue - when I run from shortcut it doesn't work, but if I run from terminal with wish, all works, hm

**Comment by aplsimple** [comment]
If you used alited's installer, in the installed directory there is alited.sh (or alited.bat for Windows), which can be used to run alited. In such case you can add to the files some initialisation like this:

```
# in Linux:
export TCLLIBPATH="~/myPrj/package1 ~/myPrj/package2"
# in MS Windows:
set TCLLIBPATH=~/myPrj/package1 ~/myPrj/package2
cd ~/PG/alited/src
tclsh src/alited.tcl
```
...and run alited with those files. Or make the files manually.

In alited help (menu Help/alited), see "Using tclkits" section.

**Comment by georgtree** [comment]
Got it, thank you!
