### ISSUE TITLE
Scroll with pressed Scroll wheel doesn't update line numbers

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#28]
Hello!
I found a small issue, it doesn't affect anything in my case, just a curious finding:
when I use pressed scroll wheel for fast scrolling, line numbers are freeze and update only when I place cursor again on the text area.
Regards, George.

**Comment by par7133** [comment]
Just a small hint to Alex about RADXIDE on the scrolling with line numbers.

Found some small bugs of this kind in Alited and finding myself in the need to reproject
the RADXIDE mainWindow (cutting on gui elements and inserted some new ones in RADXIDE)
I adopted a different approach from Alited.. connecting directly the vertical scrollbar events to the
textareas scrolling events. You can find the code in https://github.com/RADXIDE/win.tcl noted
as "Scrollbars amenities" in makeMainWindow. The code is all but perfect, but you can get
maybe inspired by this different approach.

I get this time also to suggest Alex (and I hope to not have already noted you about this) that
opening Alited on a two screens station the screen geometry calculation should be improved,
you can find this code in https://github.com/RADXIDE/win.tcl: proc centerWin {win wwidth wheight} {}


-CC

Jul 29, 2024 14:32:13 georgtree ***@***.***>:

**Comment by aplsimple** [comment]
Hi George,

What is the pressing scroll wheel for fast scrolling? I can not achieve the fast scrolling, however strongly pressing the wheel, and as such the issue as well.

Share please how you achieve it. Or you just have some cool mouse device, if pressing the wheel incessantly means the incessant (to bottom?) scrolling, not?

**Comment by aplsimple** [comment]
Hi Daniele,

Thanks for your kind tips. I'll look at **centerWin** proc of your **win.tcl**.

As for scrolling, I should understand the issue first.

**Comment by georgtree** [comment]
> Hi George,
> 
> What is the pressing scroll wheel for fast scrolling? I can not achieve the fast scrolling, however strongly pressing the wheel, and as such the issue as well.
> 
> Share please how you achieve it. Or you just have some cool mouse device, if pressing the wheel incessantly means the incessant (to bottom?) scrolling, not?

Hello!
I attached video to this post, yes I have ability to press and hold scroll wheel.

https://github.com/user-attachments/assets/65beaba0-7439-4eb6-b799-7526ebd93041

**Comment by aplsimple** [comment]
Hopefully,  in v1.8.6.3 this scrolling mode works with updating the line numbers gutter.

However, I should note that this mode can be treacherous. When you have a selected text and press the mouse wheel to scroll and then (changing your mind) immediately release the wheel - the selection will be inserted in the text, unintentionally. These insertions might be good in other cases, but not with the cancelled scrolling.

Also I noticed that this scrolling mode is implemented in Tk, and not in other GUIs. Perhaps, they are made to be more cautious in order to avoid this unintentional insertions.

**Comment by georgtree** [comment]
Thank you, I will test it today.
Regarding this scroll mode - yeah I also noticed this unintentional paste. So question - is it possible to speed up the conventional scrolling?

**Comment by georgtree** [comment]
Just tried on my Ubuntu, still doesn't work :(
Version is v1.8.6.3 (31 Jul'24)

**Comment by georgtree** [comment]
Tested a little bit more - when scroll wheel is pushed at text, lines numbers are fixed, but when button is pushed at scroll widget, lines numbers are not fixed

**Comment by georgtree** [comment]
Additional update - in detached window all works well, in main - not as I mentioned before

**Comment by aplsimple** [comment]
Fixed in v1.8.6.4.

**Comment by georgtree** [comment]
Thank you!
