### ISSUE TITLE
Folder treeview folding after pressing update button.

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#29]
Hello!
I also found an issue (but maybe it was done by purpose?) :
When I press update button in folder view, the branch that contains updates (new files or removing files) folded and I have to manually unfold them again.
Thank you in advance!

**Comment by aplsimple** [comment]
OK, the open branches should normally remain open at refreshing the tree, if they weren't deleted. To do on tomorrow.

**Comment by aplsimple** [comment]
Fixed in v1.8.6.3.
There might be little (hopefully consistent) peculiarities, depending on changes made to the project directory.

**Comment by georgtree** [comment]
I tested, now it works well, thank you!
