### ISSUE TITLE
Can't use Fossil commands

### ISSUE THREAD

**Issue by blacksqr** [aplsimple/alited#3]
Trying to use commands from the fossil menu, like "fossil changes", "fossil extras" and "fossil diff" result in an error

I have fossil 2.17 installed and in my executable path.  The root directory of my project is the top directory of a fossil checkout.

I click on the F icon, the fossil menu opens, and I click on line 2 "fossil changes".  I get the error:

bad option "-fa": must be -ignorestderr, -keepnewline, or --
    while executing
"exec -ignorestderr {*}$args"
    (procedure "::em::execcom" line 3)
    invoked from within
"::em::execcom {*}$term {*}$lang {*}$fs {*}$geo {*}$ttl {*}$tpars  -e {*}$composite"
    (procedure "::em::xterm" line 14)
    invoked from within
"::em::xterm $sel $amp"
    (procedure "::em::term" line 3)
    invoked from within
"::em::term $sel $amp"
    (procedure "shell0" line 32)
    invoked from within
"shell0 $sel $amp $silent"
    (procedure "shell1" line 6)
    invoked from within
"$c1 $typ "$seltd" $amp $silent"
    (procedure "::em::Shell_Run" line 45)
    invoked from within
"::em::Shell_Run $from $typ $c1 $s1 $amp $inpsel"
    (procedure "shell_run" line 12)
    invoked from within
"shell_run $from $typ shell1 $s1 $amp"
    (procedure "shell" line 3)
    invoked from within
"shell $typ $s1 $amp "button""
    (procedure "::em::shell_button" line 2)
    invoked from within
"{*}$comm"
    (procedure "::em::pr_button" line 8)
    invoked from within
"::em::pr_button 2 ::em::shell S: m2 &*S*"
    invoked from within
".em.fr.win.fr2.butt invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .em.fr.win.fr2.butt"
    (command bound to event)

**Comment by aplsimple** [comment]
This issue is in my todo list for Windows. Hopefully it will be solved till 2022.

**Comment by blacksqr** [comment]
I should have mentioned that I'm using Linux.

The program looks like it will be very useful.  I hope you will be able to continue working on it.

**Comment by aplsimple** [comment]
Mea culpa. I overlooked the xterm of the error message.

I've changed the appropriate code. You can try it by the link:

https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip

Also, there is a setting in "Setup/Preferences/Tools" named "Linux terminal" which can be reset, e.g. I use the following:

      lxterminal --geometry=220x55

that's very nice, though xterm is sort of standard.

**Comment by blacksqr** [comment]
I see now that the root of the problem is that it's not easy in all cases to choose a command to launch a terminal window.  I'm using Kubuntu where the terminal command is "konsole".  I found the following page helpful:

https://unix.stackexchange.com/questions/137782/launching-a-terminal-emulator-without-knowing-which-ones-are-installed

That link explains that "xdg-terminal" and "x-terminal-emulator" are commonly-used aliases for a terminal window command.

I put the value "x-terminal-emulator" in "Setup/Preferences/Tools/Linux terminal" and the fossil tools worked as expected.

Would it be practical to use tkcon as a final fallback?

**Comment by aplsimple** [comment]
Thank you for your kind advice. I'll put x-terminal-emulator into a writeable combobox of "Linux terminal" setting along with xterm and lxterminal.
