### ISSUE TITLE
Error when try to save file in detached window

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#30]
Hello!
I got this error when I try to save file that was changed in detached window:
![image](https://github.com/user-attachments/assets/98cf4bd4-c9db-4702-b994-dbb566477dc2)

Regards, George.

**Comment by aplsimple** [comment]
Thanks for the feedback.
It was my oversight. To be fixed in the github commit, tomorrow.

**Comment by aplsimple** [comment]
Fixed in v1.8.6.3.

**Comment by georgtree** [comment]
Just tested, all works well!
