### ISSUE TITLE
How to open multiple instances of alited

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#31]
Hello!
Is it possible to open two versions of alited at the same time?
When I try to open second instance it open the same window.
I suspect that for that I have to make two folders with two independent versions?
Thank you in advance!

**Comment by aplsimple** [comment]
For this, open Preferences/Saving tab and clear **Port to listen alited** field.

**Comment by aplsimple** [comment]
Also, I should add that having multiple instances of alited is especially good when you run it with different configurations. Thus you can work with different **types of projects**.

To run alited with another (other than default) configuration, add its config directory as the *first argument* of alited call, e.g.

`tclsh alited.tcl ~/.config/alited2
`

where **~/.config/alited2** should be an existing directory.

**Comment by aplsimple** [comment]
Another way to have multiple instances of alited is using DEBUG argument of alited call, e.g.

`tclsh alited.tcl ~/.config/alited2 DEBUG`

**Comment by georgtree** [comment]
Hello, thank you a lot!
