### ISSUE TITLE
Error if file is called nn.tcl

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#32]
Error if file is called nn.tcl under Windows 10.
If you rename it to kn.tcl there are no errors.
Not under Linux.

Tried with two versions:
alited v1.8.5a2 (28 May'24),
alited v1.8.6.4 (1 Aug'24)

couldn't read file "F:\\tcltk\\project\\pdfviewer\\windows\": permission denied
Der Befehl "n.tcl"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Drücken Sie eine beliebige Taste . . .

**Comment by aplsimple** [comment]
Yes, George, it is the old issue of e_menu at running apps in Windows. You've rightly noticed that names containing \n (and obviously \r, \t etc) are treated wrong in Windows' alited. Thanks to Bill Gates who'd mixed the backslash "\" (the standard escaping character) with the Windows file parts divider. As if the simple slash "/" was "an old school style" or looking unnatural in 1980 huh. The left-handers had affected here perhaps.

Whatever it takes, I'll try and solve the issue, hopefully the Windows version of alited to be not different from Linux' one.

If this attempt fails, then let alited be a Linux only app. Not so bad perspective.

**Comment by gregnix** [comment]
I always jump back and forth between Linux and Windows.
I use Alited as a reliable tool in both systems. I now understand the reason why nn.tcl and similar systems are not behaving correctly and I can work around it. For me, that would solve the problem. 
Ultimately, you don't have unlimited time.

I'm excited about Project Alited!

**Comment by aplsimple** [comment]
Hi, Gregor,

I reopen the issue just to ask you for sharing your solution, as you had noted it at closing the issue.

I tried to solve it with modifying *menu.em* in *1.8.7b2* version.

**Comment by gregnix** [comment]
No more error messages.
(Linux and Windows)
Problem solved.
+1:
