### ISSUE TITLE
Set unit tree to be folded by default

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#33]
Hello!
Is it possible to set option to force unit tree to be always folded by default?
When I save file, unit tree automatically became fully unfolded.
Thank you in advance!

**Comment by aplsimple** [comment]
Hi,

The file tree behaves this way not only at saving a file but also at opening a project file or choosing it in the tab bar, i.e. *the directory (tree branch) containing the file is expanded* to show and to select the file in it. Other branches remain as is.

The same way is with the unit tree when a unit is edited.

Well, this behaviour might be made customizable.

Though, honestly, I would not introduce an additional option for this (there are already too many of them).

Perhaps it would make sense to "freeze" the tree after choosing "Contract All" action. And "unfreeze" at "Expand All". And the last "freeze/unfreeze" mode to be default for future sessions.

**Comment by georgtree** [comment]
Hello, yeah that would be great to make it behavior like that, thank you 😄

**Comment by aplsimple** [comment]
A bit better behaviour in v1.8.7b1, still the problem isn't solved completely. I will write about it in more details tomorrow.
---
But, George, why so much attention to the file tree?

I personally use it rather rarely, mostly when I want to see the list of files open (or open not) in a current file's directory. They are highlighted or not, at that. And then I decide to open or to close the appropriate files.

If I want to access the project files quickly (esp. when they are numerous), I use F9 key to bring up their list with option to detach (tear off) it. To have the list sorted, I use **Tools/File list/Sort** switch. Or just use the context menu of the tab bar.

When you switch the unit tree to the file tree, you lose two nice features: the unit tree and the last visited/favourite units. The last visited/favourite units' list is imho much better for navigating the project files than the file tree.

**Comment by georgtree** [comment]
Hello!
In my initial post I spoke about unit tree, not the file tree. I use unit tree a lot and this is a killer feature for me :)

**Comment by aplsimple** [comment]
Whatever happens the file tree's behaviour has been improved a little :)

**Comment by georgtree** [comment]
I uploaded the file with issue:

https://github.com/user-attachments/assets/649cc0d9-1e66-4289-98f2-63b8e62268c4

**Comment by aplsimple** [comment]
Yes, I see. The branches should not be expanded without necessity.
It's just because my thoughts are somewhere else that I went the wrong way, excuses.

**Comment by aplsimple** [comment]
Hi, George,

I've changed the handling "Contract All" button of unit/file tree's tool bar, this way:

   - the button's icon is changed
   - for file tree, this mode works per project
   - for unit tree, this mode works per edited file (and can be switched in projects, if the file is edited in various projects)
   - when the tree is updated, alited tries to expand a unit/file in its branch, contracting other branches
   - clicking "Expand All" restores the old manner of handling trees, i.e. expanding trees
   - current modes of "Contract All" button are saved for future openings of projects

**Comment by georgtree** [comment]
Thank you very much !
