### ISSUE TITLE
Automatic expansion doesn't work for detached window

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#36]
Hello!
On Windows there is a feature to move window to the edge of screen and then it expand app window to the whole screen, or to the exact half of the screen. It works for main window, but not for detached one.
Thank you in advance!

**Comment by aplsimple** [comment]
You want me to compete with MS Windows?

All I can do with all (or nearly all) windows of alited is to try and save their last geometries, to restore those geometries in future. **Including the detached windows**.

I should note that alited is one of not so many apps that tries to do this as where as possible.

Still, there are alited's dialogues without this "save/restore geometry" feature, all are when it's reasonable. Of course it is not an absolute truth, so it might be pointed when it's not reasonable.

**Comment by georgtree** [comment]
Hello!
Sorry, I'm not too involved in GUI development to judge the workload of particular feature, so it's fair enough :)
