### ISSUE TITLE
Add option to put new file tab at the end of tab list

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#37]
Hello!
Is it possible to add ability to add new tabs at the of the tab list, not to the start?
Thank you in advance!

**Comment by aplsimple** [comment]
Right click the tab bar to open its context menu, then choose "Files to Beginning" to switch it off.

I am very fond of placing tabs to the beginning as default. Though, indeed, in some cases it should be switched off, for a while.

Also I should note placing selected tab(s) after a chosen one, available in the tab bar's context menu. To select multiple tabs, use Control key + left click.

The tab bar's context menu is one of alited's gems.🤣

See also the appropriate demo, at ~5 minute:

https://github.com/aplsimple/alited/releases/download/Demos_of_alited-1.6/2.Projects_alited-1.8.mp4

**Comment by georgtree** [comment]
Thank you, sorry for dumb questions, sometimes I miss the obvious things :(
