### ISSUE TITLE
Tree build: filenames containing double quotes hangs and filenames containing spaces get truncated

### ISSUE THREAD

**Issue by par7133** [aplsimple/alited#39]
Hello Alex,

I found these two cases in RADXIDE tree building code, I do not know if by case Alited is also affected:
1. filenames containing double quotes hang the application;
2. filenames containing spaces get truncated to the leftmost part.
Actually I'm investigating how to fix the code in RADXIDE. 
I'd ask you with courtesy to let me know if by case you already solved them.
I attach the debug log of the hang for the filenames containing double quotes.
Thanks,

-Dan
[debug.log](https://github.com/user-attachments/files/17284295/debug.log)

**Comment by par7133** [comment]
My patch attached. Actually I ignore d == "y" setting always d = " ". I 'm not sure about the cons of this couse RADXIDE does not use "y" in file names.
[patch.txt](https://github.com/user-attachments/files/17285058/patch.txt)

**Comment by aplsimple** [comment]
Hi Dan,

Thanks for the feedback.

Somewhere in docs I strongly recommend to avoid spaces in file names of Tcl projects, not to say about double quotes. Nonetheless such names are nicely displayed in alited's file tree, as well as unit names in the unit tree.

I don't know why your tree needs the additional actions to fix this.

Perhaps you populate the tree at creating it? I firstly create the tree and then run "after idle" with the populating procedure.

**Comment by par7133** [comment]
Thanks to your hints, after awaking, I produced a new patch for you encopassing the "y" to manually hide files.

Hope it is useful.

[patch_last.txt](https://github.com/user-attachments/files/17289537/patch_last.txt)

**Comment by par7133** [comment]
patch fixed

[patch_latest.txt](https://github.com/user-attachments/files/17290051/patch_latest.txt)

**Comment by par7133** [comment]
It is already a 4 days that I'm successfully running patched version of RADXIDE.
Hope you can enjoy the patch for dirContent.

-Dan

**Comment by aplsimple** [comment]
Good. That's okay with my tree. I'm glad that with yours too. You might close this issue.

I should note however that some lines of your code might be simpler.

**Firstly**, use braces in [expr] command. This is recommended for performance. This is so in most cases: there are rather rare cases when the braces aren't used, e.g. in command substitutions.

See details in:
https://tcl.tk/man/tcl/TclCmd/expr.htm

So, istead of

```
expr [string length $fname]-2
```

use

```
expr {[string length $fname]-2}
```

**Secondly**, this snippet

```
set start [expr [string length $fname]-2]
set last [expr [string length $fname]-1]
set d [string range $fname $start $last]
```

could be nicely substituted with the following

```
set d [string range $fname end-1 end]
```

See https://tcl.tk/man/tcl/TclCmd/string.htm about STRING INDICES.

**Comment by par7133** [comment]
Thank you Alex, well received.

I wrote the last post to close the issue too... but it seems I can't do it from my side.




-Dan

Oct 12, 2024 07:11:08 Alex Plotnikov ***@***.***>:
