### ISSUE TITLE
Can't type tabs in text editor pane

### ISSUE THREAD

**Issue by blacksqr** [aplsimple/alited#4]
Alited version 1.0.6b26 on Linux

When I try to type a tab character into a file opened for editing, either nothing happens, or what looks like a mini-widget appears near the cursor and typing is disabled until I hit the escape key.

To reproduce:

Open the default project

Double-click on README.md to open in text edit pane.  First line is highlighted and cursor is at beginning of file.  When I hit the space bar space characters are inserted, but when I hit the tab key nothing happens.  I can click to any place in the file and get the same behavior

Double-click on src/about.tcl to open in text edit pane.  Move cursor to first line of Tcl code (line 12).  Hit tab key.  A very thin mini-widget (?) appears on line 13.  Further typing is disabled until I hit the space bar or the escape key.

**Comment by aplsimple** [comment]
The Tab key is used for the command completion. This default usage can be redefined in **"Preferences/Keys"**.

In other IDEs & editors, I've experienced problems with Tab (and its indentations mixed with spaces') so often that I decided to use it as "command complete" tool,  by default.

Thus, no Tab indentation by default in alited. Let it be a freak of the author:)

**Comment by aplsimple** [comment]
The command completion works in alited like this: press e.g. "l" letter, then Tab - and **list** commands will be shown along with other commands beginning with "l" letter, so you can choose any one.

This, probably, isn't much useful, but when you have a lot of, e.g., nsp::* commands with long names, you can press "ns" and Tab, to choose the wanted. And its full name will be inserted in the text buffer.

The command completion might be enhanced with inserting a whole declaration of chosen command, not only its name. Perhaps, in a next version.

**Comment by blacksqr** [comment]
Note from attached screenshot that when I created a new file, typed "name" and hit tab, a tiny narrow window appeared where any contents are unreadable.

![Screenshot_20211229_122917](https://user-images.githubusercontent.com/395305/147692804-2d595bcc-a57b-4419-8ba8-7c253e3b59d4.png)

**Comment by aplsimple** [comment]
Though I couldn't reproduce this bug, some changes are made to complete.tcl.

The updated v1.0.6.1 available at
https://chiselapp.com/user/aplsimple/repository/alited/zip/trunk/alited.zip

![alited_bug](https://user-images.githubusercontent.com/37333988/147725065-50ebe7c6-e334-4e31-973d-c228e4d089ba.png)

**Comment by blacksqr** [comment]
I see the same behavior as before in v1.0.6.1.  If you can't reproduce it then it's likely a bug in Tk's interaction with my xwindows server or window manager.

As a workaround, I added the following line after line 129 in complete.tcl:

`after idle [subst -nocom {wm geometry $win [regsub {([0-9]+x[0-9]+)} [wm geometry $win] 220x325]}]`

**Comment by aplsimple** [comment]
Hi Steve! Happy New Year!

Thank you so much for your generous participation! I will insert your bugfix into v1.0.6.2.

At that I'd wish to track the bug so that, if it's a bug of Tcl/Tk, it could be reported onto Tcl/Tk codebase.

Could you share details of your system? Ubuntu & Tcl version, WM etc. All of them could be installed on my machine's testing partition.

Also, there is other way. I might reduce the issue code to a very short script for the bug to be reproduced on your machine, without any aliteds.

In the new year! Let it be better than 2021 :)

**Comment by blacksqr** [comment]
Happy New Year to you.  I am enjoying using alited and I feel it has increased my productivity so far.  I'm rooting for it to improve and succeed.

System info:

Tcl/Tk: 8.6.11
Kubuntu 16.04
KDE Plasma version 5.5.5
