### ISSUE TITLE
Error when saving file after preferences change

### ISSUE THREAD

**Issue by blacksqr** [aplsimple/alited#5]
I open the default project and open about.tcl

I edit about.tcl

I open the Preferences window and go to Keys

I change the command completion character and click save

A window comes up asking if I want to restart.  I click yes.

A window comes up saying about.tcl is not saved and do I want to save it.  I click yes.

Popup with following error appears:

invalid command name "::alited::alitedpav"
    while executing
"$obPav Tree"
    (procedure "::alited::tree::RecreateTree" line 7)
    invoked from within
"::alited::tree::RecreateTree"
    ("after" script)

I click OK

Another popup appears with error message:

invalid command name "::.alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text_tab7.internal"
    while executing
"::.alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text_tab7.internal index {end -1 char}"
    ("eval" body line 1)
    invoked from within
"eval ::.alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text_tab7.internal $args"
    (procedure ".alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text_tab7" line 1)
    invoked from within
"$wtxt index {end -1 char}"
    (procedure "::alited::main::CursorPos" line 7)
    invoked from within
"::alited::main::CursorPos $wtxt"
    (procedure "::alited::main::FocusInText" line 8)
    invoked from within
"::alited::main::FocusInText tab7 .alwin.fra.fra.pan.panR.fraTop.panTop.frAText.text_tab7"
    ("after" script)

I click OK

Another popup:

invalid command name "::alited::alitedpav"
    while executing
"$::alited::obPav $v"
    (procedure "SaveIni" line 111)
    invoked from within
"SaveIni"
    (procedure "::alited::ini::SaveCurrentIni" line 12)
    invoked from within
"::alited::ini::SaveCurrentIni yes yes"
    ("after" script)

**Comment by aplsimple** [comment]
Fixed in v1.1.0a3.

There was an incorrect attempt to get a window's info, after apave object (*::alited::alitedpav*) was destroyed together with the window.
